#!/bin/sh
#      Copyright 2022. Ticos
#
#      Licensed under the Apache License, Version 2.0 (the "License");
#      you may not use this file except in compliance with the License.
#      You may obtain a copy of the License at
#
#          http://www.apache.org/licenses/LICENSE-2.0
#
#      Unless required by applicable law or agreed to in writing, software
#      distributed under the License is distributed on an "AS IS" BASIS,
#      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#      See the License for the specific language governing permissions and
#      limitations under the License.

set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p python3-ticos-gateway 
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p python3-ticos-gateway  || true
fi

# End automatically added section
echo "Installing jsonschema"
sudo rm -rf /usr/lib/python3/dist-packages/jsonschema
CURRENT_USER=$USER
sudo pip3 install --upgrade jsonschema==3.1.1
#sudo pip3 install --upgrade bluepy
sudo pip3 install --upgrade pyrsistent --progress-bar off -qqq || echo "OK"
sudo pip3 install --upgrade importlib --progress-bar off -qqq || echo "OK"
sudo pip3 install --upgrade importlib-metadata --progress-bar off -qqq || echo "OK"
sudo cp -a -r /etc/ticos-gateway/extensions /var/lib/ticos_gateway/
sudo rm -r /etc/ticos-gateway/extensions
sudo usermod -a -G dialout $CURRENT_USER
sudo usermod -a -G ticos_gateway $CURRENT_USER
sudo chown ticos_gateway:ticos_gateway /var/log/ticos-gateway/ -R
sudo chown ticos_gateway:ticos_gateway /var/lib/ticos_gateway/ -R
sudo chown ticos_gateway:ticos_gateway /etc/ticos-gateway/ -R
sudo sed -i 's/\.\/logs/\/var\/log\/ticos-gateway/g' /etc/ticos-gateway/config/logs.conf >> /etc/ticos-gateway/config/logs.conf
echo "Installation completed"
echo "Enabling daemon..."
sudo pidof systemd && sudo systemctl enable ticos-gateway || echo "Systemctl not found"
#echo "Daemon starting..."
sudo pidof systemd && sudo systemctl start ticos-gateway || echo
echo -e "\e[96mTicos Gateway \e[92mhas been installed. Have a nice day \e[93m\e[5m:)\e[25m\e[39m"
