version: '3.0'
services:
  ticos-gateway:
    restart: always
    image: "ticos/ticos-gateway"
    # Ports (Required for REST connector)
    ports:
      - "5000:5000"
    volumes:
      - ~/.ticos-gateway/config:/ticos_gateway/config
      - ~/.ticos-gateway/logs:/ticos_gateway/logs
      - ~/.ticos-gateway/extensions:/ticos_gateway/extensions